ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock
RUN yarn install --frozen-lockfile

COPY . .

RUN yarn bootstrap
RUN rm -rf /app/packages/server/dist/
RUN rm -rf /app/packages/client/dist/
RUN yarn build


FROM node:$NODE_VERSION-buster-slim as production
WORKDIR /app

EXPOSE $SERVER_PORT
CMD [ "node", "/app/packages/server/dist/index.js" ]