ARG NODE_VERSION=16
ARG SERVER_PORT=3001

FROM node:$NODE_VERSION-buster as base

WORKDIR /app

FROM base as builder

COPY package.json yarn.lock

RUN npm config rm proxy
RUN npm config rm https-proxy
RUN yarn config set network-timeout 600000 -g

RUN yarn install --frozen-lockfile

COPY . .

RUN rm -rf ./packages/server/dist/
RUN rm -rf ./packages/client/dist/
RUN yarn bootstrap
RUN yarn build

EXPOSE $SERVER_PORT
CMD [ "node", "./packages/server/dist/index.js" ]